<a href="https://colab.research.google.com/github/darialrsm/Machine-learning/blob/main/%D0%A5%D0%B0%D1%85%D0%BB%D1%94%D0%B2%D0%B0_%D0%BF%D1%80_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Хахлєва Дар'я, ФІТ 4-11

In [2]:
import numpy as np

1. Задати вектор, що складається з перших п'яти натуральних чисел

In [3]:
vector = np.array([1, 2, 3, 4, 5])

vector

array([1, 2, 3, 4, 5])

2. Транспортувати вектор

In [5]:
v1 = np.matrix([1, 2, 3, 4, 5])

print(v1)
v2 = v1.T
v2

[[1 2 3 4 5]]


matrix([[1],
        [2],
        [3],
        [4],
        [5]])

3. Напишіть функцію, яка перевертає веткор у зворотньому порядку

In [6]:
v = np.array([1, 2, 3, 4, 5])

print(v[::-1])

[5 4 3 2 1]


In [8]:
v = np.flip(v)
v

array([1, 2, 3, 4, 5])

4. Обчислити середнє значення ветора

In [9]:
print(np.mean(v))

3.0


5. Знайти найбільший та найменший елементи веткора

In [10]:
print(np.max(v))
print(np.min(v))

5
1


6. Обчислити скалярний добуток двох векторів

In [11]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(np.dot(v1, v2))
print(v1*v2)

32
[ 4 10 18]


7. Напишіть функцію, яка нормалізує вектор (зводить до одиничної довжини)

In [12]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)

print(norm)

v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

8. Задайте два веткори. Визначте, чи є вони ортогональними (скалярний добуток має дорівнювати нулю)

In [13]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

np.dot(v1, v2)

np.int64(0)

9. Визначити унікальні елементи вектора

In [14]:
v = np.array([1, 2, 3, 2, 4, 5, 3, 3])

np.unique(v)

array([1, 2, 3, 4, 5])

10. Різниця, сума, добуток та частка векторів

In [16]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


11. Перевірити, чи дорівнює довжина вектора 5

In [19]:
v = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(v)

np.isclose(length, 5)

np.False_

12. Задати матрицю, заповнену випадковими числами

In [20]:
a = np.random.randint(0, 11, (3, 3))
a

array([[10,  6,  5],
       [ 6,  3,  2],
       [ 6,  7,  3]])

13. Обчислити визначник матриці

In [21]:
np.linalg.det(a)

np.float64(34.00000000000002)

14. Знайти обернену матрицю

In [22]:
np.linalg.inv(a)

array([[-1.47058824e-01,  5.00000000e-01, -8.82352941e-02],
       [-1.76470588e-01, -1.30614473e-16,  2.94117647e-01],
       [ 7.05882353e-01, -1.00000000e+00, -1.76470588e-01]])

15. Розв'язати систему лінійних рівнянь Ax=b, де А = матриця коефіцієнтів, b - вектор вільних членів

In [23]:
a = np.array(([1, 3, -4], [0, 2, -3], [-2, 2, 5]))
b = np.array([5, 3, 4])

x = np.linalg.solve(a, b)
print(x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print(x1)

[0.38888889 1.83333333 0.22222222]
[0.38888889 1.83333333 0.22222222]


16. Множення двох матриць

In [24]:
a = np.array(([1, 3, -4], [0, 2, -3], [-2, 2, 5]))
b = np.array([5, 3, 4])

np.dot(a, b)

array([-2, -6, 16])

In [25]:
a = np.matrix([[1, 3, -4], [0, 2, -3]])
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(a)
print(b)
print(np.dot(a, b))

[[ 1  3 -4]
 [ 0  2 -3]]
[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[-1  4  7]
 [-5  0  1]]


17. Транспонування матриці

In [26]:
print(a.T)
print(b.T)

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


In [27]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0]
 [ 3  2]
 [-4 -3]]
[[5 2 3]
 [3 3 2]
 [4 5 3]]


18. Перевірка симетричності матриці

In [28]:
matrix = np.matrix([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
np.allclose(matrix, matrix.T)

True

19. Обчислення сліду матриці

In [29]:
np.trace(matrix)

np.int64(6)

20. Сума матриць

In [31]:
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


21. Піднесення матриці до ступеня

In [32]:
a = np.matrix([[1, 2], [3, 4]])

np.linalg.matrix_power(a, 2)

matrix([[ 7, 10],
        [15, 22]])

22. Сортування рядків або стовпців матриці

In [33]:
b = np.matrix([[5, 3, 4], [2, 3, 5], [3, 2, 3]])

print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [34]:
a = np.array([[1, 4], [3, 1]])

print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


In [35]:
print(np.sort(a, axis = 0))
print(np.sort(a, axis = 1))

[[1 1]
 [3 4]]
[[1 4]
 [1 3]]


23. Підрахувати суму елементів кожного рядку матриці та записати відповідь, як веткор-стовпчик

In [36]:
row_sums = np.sum(a, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[5]
 [4]]
