Варіант №19

Імпортування бібліотеки та перевірка версії

In [2]:
import numpy as np
np.__version__

'2.0.2'

1. Створіть одновимірний масив (вектор) з добутками парних чисел на їхні попередні
непарні числа, починаючи з 2, та виведіть його значення. (перші 10 парних чисел)

In [3]:
# Перші 10 парних чисел
even_numbers = np.arange(2, 21, 2)

# Попередні непарні числа
odd_numbers = even_numbers - 1

# Добутки парних та непарних чисел
result = even_numbers * odd_numbers

print("Парні числа: ", even_numbers)
print("Попередні непарні числа: ", odd_numbers)
print("Результат (вектор):", result)

Парні числа:  [ 2  4  6  8 10 12 14 16 18 20]
Попередні непарні числа:  [ 1  3  5  7  9 11 13 15 17 19]
Результат (вектор): [  2  12  30  56  90 132 182 240 306 380]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
квадратів випадкових цілих чисел від 1 до 100

In [6]:
# Створюємо матрицю за заданими параметрами
matrix = np.random.randint(1, 101, (3, 3))
matrix

array([[75, 46, 63],
       [ 5, 81, 88],
       [41, 72, 40]])

In [7]:
# Створюємо матрицю зі значеннями квадратів
sq_matrix = matrix**2
sq_matrix

array([[5625, 2116, 3969],
       [  25, 6561, 7744],
       [1681, 5184, 1600]])

3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами від -2 до
2 та знайдіть середнє за модулем значення його елементів

In [8]:
# Створюємо матрицю за заданими параметрами
matrix = np.random.randint(-2, 3, (5, 5))
matrix

array([[-2,  2, -2,  0,  1],
       [-2, -1,  0, -2, -1],
       [ 1, -1, -2, -2,  1],
       [ 1, -1, -2, -2,  0],
       [ 1,  2,  0,  1,  1]])

In [9]:
# Матриця із модулями значень
abs_matrix = np.abs(matrix)
abs_matrix

array([[2, 2, 2, 0, 1],
       [2, 1, 0, 2, 1],
       [1, 1, 2, 2, 1],
       [1, 1, 2, 2, 0],
       [1, 2, 0, 1, 1]])

In [10]:
# Знаходимо середнє значення за модулем
np.mean(abs_matrix)

np.float64(1.24)

4. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення.


In [11]:
# Створюємо матрицю заданими параметрами, значення округлені до сотих

matrix = np.round(np.random.rand(5, 5), 2)
print("Початкова матриця")
print(matrix)

# Середнє значення
mean = np.round(np.mean(matrix), 2)
print("Середнє значення: ", mean)

# Значення, що менші за середнє
less_than_mean = matrix[matrix < mean]
print("Значення, що менші за середнє: ", less_than_mean)

# Обчислення суми
sum = np.sum(less_than_mean)
print("Сума значень, що менші за середнє: ", sum)

Початкова матриця
[[0.15 0.94 0.73 0.52 0.89]
 [0.91 0.06 0.8  0.66 0.29]
 [0.36 0.21 0.41 0.3  0.18]
 [0.39 0.84 0.39 0.51 0.67]
 [0.56 0.66 0.27 0.21 0.78]]
Середнє значення:  0.51
Значення, що менші за середнє:  [0.15 0.06 0.29 0.36 0.21 0.41 0.3  0.18 0.39 0.39 0.27 0.21]
Сума значень, що менші за середнє:  3.22


5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими дійсними
числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання
ta множення.

In [13]:
# Створюємо масиви, значення округлюємо до тисячних
x1 = np.round(np.random.uniform(-2, 2, 7), 3)
x2 = np.round(np.random.uniform(-2, 2, 7), 3)

print("Масив 1: ", x1)
print("Масив 2: ", x2)

add = x1+x2
sub = x1-x2
mult = x1*x2

print("Резулультат додавання: ", add)
print("Резулультат віднімання: ", sub)
print("Резулультат множення: ", mult)

Масив 1:  [-0.519  1.724 -0.096 -0.185 -1.693  1.962  1.866]
Масив 2:  [-1.372  1.603  0.761 -0.459  0.525  1.706 -1.994]
Резулультат додавання:  [-1.891  3.327  0.665 -0.644 -1.168  3.668 -0.128]
Резулультат віднімання:  [ 0.853  0.121 -0.857  0.274 -2.218  0.256  3.86 ]
Резулультат множення:  [ 0.712068  2.763572 -0.073056  0.084915 -0.888825  3.347172 -3.720804]


6. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 7 до 17 та
знайдіть їх добуток

In [19]:
# Створюємо матриці
matrix1 = np.random.randint(7, 18, (4, 4))
matrix2 = np.random.randint(7, 18, (4, 4))
# Знаходимо добуток
mult_matrix = np.dot(matrix1, matrix2)

print("Матриця 1: ")
print(matrix1)
print("Матриця 2: ")
print(matrix2)
print("Добуток матриць: ")
mult_matrix

Матриця 1: 
[[13 16 17 11]
 [ 8 15 12  7]
 [13 16 17  8]
 [15 11 11 14]]
Матриця 2: 
[[10  9 12 13]
 [11 13 15 16]
 [10 17  7  9]
 [15 17 11 17]]
Добуток матриць: 


array([[641, 801, 636, 765],
       [470, 590, 482, 571],
       [596, 750, 603, 714],
       [591, 703, 576, 708]])

7. Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами
в діапазоні від 1 до 6 та перемножте їх між собою.


In [21]:
# Створюємо матриці
m1 = np.random.randint(1, 7, (4, 2))
m2 = np.random.randint(1, 7, (2, 5))
# Знаходимо добуток
m3 = np.dot(m1, m2)
print("Матриця 1: ")
print(m1)
print("Матриця 2: ")
print(m2)
print("Добуток матриць: ")
m3

Матриця 1: 
[[1 1]
 [4 1]
 [2 1]
 [4 5]]
Матриця 2: 
[[6 1 6 2 6]
 [4 3 5 1 2]]
Добуток матриць: 


array([[10,  4, 11,  3,  8],
       [28,  7, 29,  9, 26],
       [16,  5, 17,  5, 14],
       [44, 19, 49, 13, 34]])

8.  Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть її обернену матрицю

In [22]:
# Створюємо матрицю
m = np.random.randint(1, 11, (2, 2))

# Знаходимо обернену матрицю
inv_m = np.linalg.inv(m)

print("Початкова матриця: ")
print(m)
print("Обернена матриця: ")
print(inv_m)

Початкова матриця: 
[[ 4  7]
 [ 5 10]]
Обернена матриця: 
[[ 2.  -1.4]
 [-1.   0.8]]


9. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 10 до 50 та транспонуйте її.

In [25]:
# Створюємо матрицю
m = np.round(np.random.uniform(10, 50, (3, 3)), 2)

# Транспонуємо матрицю
transp_m = m.T

print("Початкова матриця: ")
print(m)
print("Обернена матриця: ")
print(transp_m)

Початкова матриця: 
[[13.55 29.62 49.49]
 [13.52 32.61 40.44]
 [20.4  42.71 17.08]]
Обернена матриця: 
[[13.55 13.52 20.4 ]
 [29.62 32.61 42.71]
 [49.49 40.44 17.08]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [29]:
# Створюємо матрицю та вектор
m = np.random.randint(1, 11, (3, 4))
v = np.random.rand(4, 1)

# Знаходимо добуток
res = np.dot(m, v)

print("Матриця: ")
print(m)
print("Вектор: ")
print(v)
print("Добуток матриці на вектор: ")
res

Матриця: 
[[ 6 10  7  7]
 [ 3  6  9  6]
 [ 6  2  9  9]]
Вектор: 
[[0.87081402]
 [0.42151867]
 [0.87817414]
 [0.62227988]]
Добуток матриці на вектор: 


array([[19.94324898],
       [16.77880065],
       [19.57200765]])

11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор

In [33]:
# Створюємо матрицю та вектор
m = np.round(np.random.rand(2, 3), 2)
v = np.random.randint(1, 11, 3)

# Знаходимо добуток
res = np.dot(m, v)

print("Матриця: ")
print(m)
print("Вектор: ")
print(v)
print("Добуток матриці на вектор: ")
res

Матриця: 
[[0.47 0.26 0.14]
 [0.32 0.26 0.44]]
Вектор: 
[6 3 5]
Добуток матриці на вектор: 


array([4.3, 4.9])

12. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть добуток елементів діагоналей обох матриць (окремо).

In [35]:
# Створюємо матриці
m1 = np.random.randint(1, 6, (3, 3))
m2 = np.random.randint(1, 6, (3, 3))

# Елементи діагоналей
diag1 = np.diag(m1)
diag2 = np.diag(m2)

# Добуток елементів діагоналі
prod_diag1 = np.prod(diag1)
prod_diag2 = np.prod(diag2)

print("Матриця 1:")
print(m1)
print("Матриця 2:")
print(m2)

print("Діагональні елементи матриці 1:", diag1)
print("Діагональні елементи матриці 2:", diag2)

print("Добуток елементів діагоналі матриці 1:", prod_diag1)
print("Добуток елементів діагоналі матриці 2:", prod_diag2)

Матриця 1:
[[3 1 3]
 [5 3 1]
 [2 2 3]]
Матриця 2:
[[3 2 1]
 [4 3 4]
 [2 2 4]]
Діагональні елементи матриці 1: [3 3 3]
Діагональні елементи матриці 2: [3 3 4]
Добуток елементів діагоналі матриці 1: 27
Добуток елементів діагоналі матриці 2: 36


13. Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть суму їх елементів

In [40]:
# Створюємо матриці
m1 = np.round(np.random.uniform(-1, 1, (3, 3)), 2)
m2 = np.round(np.random.uniform(-1, 1, (3, 3)), 2)

# Знаходимо суму елементів кожної матриці
sum1 = np.sum(m1)
sum2 = np.sum(m2)

# Загальна сума
total = sum1+sum2

print("Матриця 1:")
print(m1)
print("Матриця 2:")
print(m2)

print("Сума елементів матриці 1:", sum1)
print("Сума елементів матриці 2:", sum2)

print("Загальна сума елементів двох матриць", total)

Матриця 1:
[[ 0.57  0.62 -0.3 ]
 [ 0.94  0.27  0.32]
 [-0.09 -0.15  0.18]]
Матриця 2:
[[ 0.57  0.33  0.24]
 [-0.39  0.73  0.39]
 [ 0.44 -0.91  0.01]]
Сума елементів матриці 1: 2.36
Сума елементів матриці 2: 1.41
Загальна сума елементів двох матриць 3.7699999999999996


14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -3 до 3 та знайдіть найбільший елемент матриці.

In [41]:
# Створюємо матрицю
matrix = np.round(np.random.uniform(-3, 3, (3, 3)), 2)

# Знаходимо найбільший елемент
max_el = np.max(matrix)

print("Матриця:")
print(matrix)
print("Максимальний елемент матриці: ", max_el)

Матриця:
[[-0.87 -0.29 -1.45]
 [-1.88  0.76 -2.49]
 [-0.63  2.48 -0.28]]
Максимальний елемент матриці:  2.48


15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить кількість нульових
елементів в кожному рядку матриці

In [70]:
# Створюємо матрицю
matrix = np.round(np.random.uniform(-0.5, 0.5, (3, 3,)), 2)

zero_counts = np.sum(matrix == 0, axis=1).reshape(3, 1)

print("Матриця:")
print(matrix)

print("Вектор-стовпчик з кількістю нульових елементів у кожному рядку:")
print(zero_counts)

Матриця:
[[ 0.3  -0.38 -0.41]
 [-0.29 -0.31 -0.34]
 [ 0.06  0.13  0.26]]
Вектор-стовпчик з кількістю нульових елементів у кожному рядку:
[[0]
 [0]
 [0]]


Висновок:
У даній лабораторній роботі було зроблено завдання зі створенням різноматінтих векторів та матріць, а також виконано такі операції з ними: додавання, віднімання, множення, знаходження найбільшого елементу, транспортування та обчислення оберненої матриці, знаходження добутку елементів діагоналі та суми усіх елементів матриці.